# Conda environment specification
# To import/create a copy of the environment:
#    conda env create -f .environment.yml -n <environment_name>
name: energy_demand
channels:
- conda-forge
- defaults
dependencies:
- python=3.5
- geopandas
- haversine
- imageio
- matplotlib
- numpy
- palettable
- pyproj
- pytest  # test
- pytest-cov  # test
- recommonmark  # docs
- scipy
- sphinx  # docs
- sphinx_rtd_theme  # docs
- pip:
  - isoweek
  - ruamel.yaml==0.15.50